name: Snap2Txt on every commit

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snap2txt:
    uses: overandor/snap2txt/.github/workflows/reusable-snap2txt-v2.yml@0e0457da0cbdeff7a7c2c68558fca124967f229e
